'use client';

import { zodResolver } from '@hookform/resolvers/zod';
import { ArrowUp } from 'lucide-react';
import { useTranslations } from 'next-intl';
import { useRouter } from 'next/navigation';
import type { KeyboardEventHandler } from 'react';
import { useForm } from 'react-hook-form';
import { z } from 'zod';

import { MessageContentSchema } from '@/api/routes/chat/schema';
import FormProvider from '@/components/forms/form-provider';
import RHFTextarea from '@/components/forms/rhf-textarea';
import { Button } from '@/components/ui/button';
import { toast } from '@/components/ui/use-toast';
import { useCreateThreadMutation } from '@/hooks/mutations/chat-mutations';
import { cn } from '@/lib/ui/cn';

// ============================================================================
// Form Schema - Reusing Backend Validation
// ============================================================================

/**
 * Chat prompt form validation schema
 * Reuses backend MessageContentSchema to ensure consistency (min 1, max 5000 characters)
 */
const chatPromptSchema = z.object({
  message: MessageContentSchema,
});

type ChatPromptFormData = z.infer<typeof chatPromptSchema>;

// ============================================================================
// Component Props
// ============================================================================

type ChatPromptFormProps = {
  className?: string;
  onThreadCreated?: (threadId: string) => void;
};

// ============================================================================
// Component
// ============================================================================

/**
 * Chat Prompt Form Component
 *
 * ChatGPT-style input form for creating new chat threads
 * - Auto-expanding textarea with Enter/Shift+Enter handling
 * - Loading state during thread creation
 * - Automatic navigation to new thread
 * - Uses default participants from backend
 *
 * Following patterns from:
 * - /src/components/forms/rhf-textarea.tsx (RHF pattern)
 * - /src/hooks/mutations/chat-mutations.ts (mutation hook)
 * - /docs/frontend-patterns.md (form architecture)
 */
export function ChatPromptForm({ className, onThreadCreated }: ChatPromptFormProps) {
  const t = useTranslations();
  const router = useRouter();
  const createThreadMutation = useCreateThreadMutation();

  // Initialize form with RHF and Zod validation
  const methods = useForm<ChatPromptFormData>({
    resolver: zodResolver(chatPromptSchema),
    defaultValues: {
      message: '',
    },
  });

  const { handleSubmit, reset, watch } = methods;
  const messageValue = watch('message');
  const isSubmitting = createThreadMutation.isPending;

  // ============================================================================
  // Form Submission Handler
  // ============================================================================

  const onSubmit = async (data: ChatPromptFormData) => {
    try {
      // Create thread with default participants
      // Backend will handle default model selection based on user's plan
      const result = await createThreadMutation.mutateAsync({
        json: {
          firstMessage: data.message,
          // Use default values for simple initial implementation
          title: 'New Chat', // Backend will auto-generate from first message
          mode: 'brainstorming',
          // Participants will be set by backend based on defaults
          participants: [
            {
              modelId: 'anthropic/claude-3.5-sonnet',
              role: 'AI Assistant',
            },
          ],
        },
      });

      if (result.success && result.data) {
        // Reset form
        reset();

        // Get thread slug (already generated by backend with AI title)
        const threadSlug = result.data.thread.slug;

        // Call optional callback with thread ID if provided
        if (onThreadCreated) {
          onThreadCreated(result.data.thread.id);
        }

        // Navigate to the new thread using slug (title already generated)
        router.push(`/chat/${threadSlug}`);

        // Show success toast
        toast({
          title: t('notifications.success.createSuccess'),
          description: t('chat.threadCreated'),
        });
      } else {
        throw new Error('Failed to create thread');
      }
    } catch (error) {
      console.error('Failed to create thread:', error);
      toast({
        title: t('notifications.error.createFailed'),
        description: t('chat.threadCreationFailed'),
        variant: 'destructive',
      });
    }
  };

  // ============================================================================
  // Keyboard Event Handler - Enter to submit, Shift+Enter for new line
  // ============================================================================

  const handleKeyDown: KeyboardEventHandler<HTMLTextAreaElement> = (e) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSubmit(onSubmit)();
    }
  };

  // ============================================================================
  // Render
  // ============================================================================

  const isDisabled = isSubmitting || !messageValue.trim();

  return (
    <div className={cn('w-full max-w-3xl mx-auto', className)}>
      <FormProvider methods={methods} onSubmit={handleSubmit(onSubmit)}>
        <div className="relative flex items-end gap-2 rounded-3xl border border-input bg-background shadow-sm focus-within:border-ring focus-within:ring-2 focus-within:ring-ring/20 transition-all">
          {/* Textarea Field */}
          <div className="flex-1">
            <RHFTextarea
              name="message"
              title="Message"
              placeholder={t('chat.input.placeholder')}
              rows={1}
              hideLabel
              className="border-0 shadow-none resize-none min-h-[52px] max-h-[200px] bg-transparent px-4 py-3 focus-visible:ring-0 focus-visible:ring-offset-0"
              disabled={isSubmitting}
              onKeyDown={handleKeyDown}
            />
          </div>

          {/* Submit Button */}
          <div className="pr-2 pb-2">
            <Button
              type="submit"
              size="icon"
              disabled={isDisabled}
              loading={isSubmitting}
              className={cn(
                'rounded-full size-9 transition-all',
                isDisabled
                  ? 'bg-muted text-muted-foreground'
                  : 'bg-primary text-primary-foreground hover:bg-primary/90',
              )}
              aria-label={t('chat.input.submit')}
            >
              {!isSubmitting && <ArrowUp className="size-4" />}
            </Button>
          </div>
        </div>

        {/* Helper Text */}
        <p className="mt-2 text-xs text-center text-muted-foreground">
          {t('chat.input.helperText')}
        </p>
      </FormProvider>
    </div>
  );
}
