/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as ProtectedChatRouteImport } from './routes/_protected/chat'
import { Route as ProtectedChatIndexRouteImport } from './routes/_protected/chat/index'
import { Route as PublicChatSlugRouteImport } from './routes/public/chat/$slug'
import { Route as ProtectedChatPricingRouteImport } from './routes/_protected/chat/pricing'
import { Route as ProtectedChatSlugRouteImport } from './routes/_protected/chat/$slug'
import { Route as ProtectedChatBillingSubscriptionSuccessRouteImport } from './routes/_protected/chat/billing/subscription-success'
import { Route as ProtectedChatBillingSubscriptionChangedRouteImport } from './routes/_protected/chat/billing/subscription-changed'
import { Route as ProtectedChatBillingFailureRouteImport } from './routes/_protected/chat/billing/failure'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedChatRoute = ProtectedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedChatIndexRoute = ProtectedChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedChatRoute,
} as any)
const PublicChatSlugRoute = PublicChatSlugRouteImport.update({
  id: '/public/chat/$slug',
  path: '/public/chat/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedChatPricingRoute = ProtectedChatPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => ProtectedChatRoute,
} as any)
const ProtectedChatSlugRoute = ProtectedChatSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProtectedChatRoute,
} as any)
const ProtectedChatBillingSubscriptionSuccessRoute =
  ProtectedChatBillingSubscriptionSuccessRouteImport.update({
    id: '/billing/subscription-success',
    path: '/billing/subscription-success',
    getParentRoute: () => ProtectedChatRoute,
  } as any)
const ProtectedChatBillingSubscriptionChangedRoute =
  ProtectedChatBillingSubscriptionChangedRouteImport.update({
    id: '/billing/subscription-changed',
    path: '/billing/subscription-changed',
    getParentRoute: () => ProtectedChatRoute,
  } as any)
const ProtectedChatBillingFailureRoute =
  ProtectedChatBillingFailureRouteImport.update({
    id: '/billing/failure',
    path: '/billing/failure',
    getParentRoute: () => ProtectedChatRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ProtectedChatRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/chat/$slug': typeof ProtectedChatSlugRoute
  '/chat/pricing': typeof ProtectedChatPricingRoute
  '/public/chat/$slug': typeof PublicChatSlugRoute
  '/chat/': typeof ProtectedChatIndexRoute
  '/chat/billing/failure': typeof ProtectedChatBillingFailureRoute
  '/chat/billing/subscription-changed': typeof ProtectedChatBillingSubscriptionChangedRoute
  '/chat/billing/subscription-success': typeof ProtectedChatBillingSubscriptionSuccessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/chat/$slug': typeof ProtectedChatSlugRoute
  '/chat/pricing': typeof ProtectedChatPricingRoute
  '/public/chat/$slug': typeof PublicChatSlugRoute
  '/chat': typeof ProtectedChatIndexRoute
  '/chat/billing/failure': typeof ProtectedChatBillingFailureRoute
  '/chat/billing/subscription-changed': typeof ProtectedChatBillingSubscriptionChangedRoute
  '/chat/billing/subscription-success': typeof ProtectedChatBillingSubscriptionSuccessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/_protected/chat': typeof ProtectedChatRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/_protected/chat/$slug': typeof ProtectedChatSlugRoute
  '/_protected/chat/pricing': typeof ProtectedChatPricingRoute
  '/public/chat/$slug': typeof PublicChatSlugRoute
  '/_protected/chat/': typeof ProtectedChatIndexRoute
  '/_protected/chat/billing/failure': typeof ProtectedChatBillingFailureRoute
  '/_protected/chat/billing/subscription-changed': typeof ProtectedChatBillingSubscriptionChangedRoute
  '/_protected/chat/billing/subscription-success': typeof ProtectedChatBillingSubscriptionSuccessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/auth/callback'
    | '/auth/sign-in'
    | '/chat/$slug'
    | '/chat/pricing'
    | '/public/chat/$slug'
    | '/chat/'
    | '/chat/billing/failure'
    | '/chat/billing/subscription-changed'
    | '/chat/billing/subscription-success'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/callback'
    | '/auth/sign-in'
    | '/chat/$slug'
    | '/chat/pricing'
    | '/public/chat/$slug'
    | '/chat'
    | '/chat/billing/failure'
    | '/chat/billing/subscription-changed'
    | '/chat/billing/subscription-success'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_protected/chat'
    | '/auth/callback'
    | '/auth/sign-in'
    | '/_protected/chat/$slug'
    | '/_protected/chat/pricing'
    | '/public/chat/$slug'
    | '/_protected/chat/'
    | '/_protected/chat/billing/failure'
    | '/_protected/chat/billing/subscription-changed'
    | '/_protected/chat/billing/subscription-success'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthSignInRoute: typeof AuthSignInRoute
  PublicChatSlugRoute: typeof PublicChatSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/chat': {
      id: '/_protected/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ProtectedChatRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/chat/': {
      id: '/_protected/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof ProtectedChatIndexRouteImport
      parentRoute: typeof ProtectedChatRoute
    }
    '/public/chat/$slug': {
      id: '/public/chat/$slug'
      path: '/public/chat/$slug'
      fullPath: '/public/chat/$slug'
      preLoaderRoute: typeof PublicChatSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/chat/pricing': {
      id: '/_protected/chat/pricing'
      path: '/pricing'
      fullPath: '/chat/pricing'
      preLoaderRoute: typeof ProtectedChatPricingRouteImport
      parentRoute: typeof ProtectedChatRoute
    }
    '/_protected/chat/$slug': {
      id: '/_protected/chat/$slug'
      path: '/$slug'
      fullPath: '/chat/$slug'
      preLoaderRoute: typeof ProtectedChatSlugRouteImport
      parentRoute: typeof ProtectedChatRoute
    }
    '/_protected/chat/billing/subscription-success': {
      id: '/_protected/chat/billing/subscription-success'
      path: '/billing/subscription-success'
      fullPath: '/chat/billing/subscription-success'
      preLoaderRoute: typeof ProtectedChatBillingSubscriptionSuccessRouteImport
      parentRoute: typeof ProtectedChatRoute
    }
    '/_protected/chat/billing/subscription-changed': {
      id: '/_protected/chat/billing/subscription-changed'
      path: '/billing/subscription-changed'
      fullPath: '/chat/billing/subscription-changed'
      preLoaderRoute: typeof ProtectedChatBillingSubscriptionChangedRouteImport
      parentRoute: typeof ProtectedChatRoute
    }
    '/_protected/chat/billing/failure': {
      id: '/_protected/chat/billing/failure'
      path: '/billing/failure'
      fullPath: '/chat/billing/failure'
      preLoaderRoute: typeof ProtectedChatBillingFailureRouteImport
      parentRoute: typeof ProtectedChatRoute
    }
  }
}

interface ProtectedChatRouteChildren {
  ProtectedChatSlugRoute: typeof ProtectedChatSlugRoute
  ProtectedChatPricingRoute: typeof ProtectedChatPricingRoute
  ProtectedChatIndexRoute: typeof ProtectedChatIndexRoute
  ProtectedChatBillingFailureRoute: typeof ProtectedChatBillingFailureRoute
  ProtectedChatBillingSubscriptionChangedRoute: typeof ProtectedChatBillingSubscriptionChangedRoute
  ProtectedChatBillingSubscriptionSuccessRoute: typeof ProtectedChatBillingSubscriptionSuccessRoute
}

const ProtectedChatRouteChildren: ProtectedChatRouteChildren = {
  ProtectedChatSlugRoute: ProtectedChatSlugRoute,
  ProtectedChatPricingRoute: ProtectedChatPricingRoute,
  ProtectedChatIndexRoute: ProtectedChatIndexRoute,
  ProtectedChatBillingFailureRoute: ProtectedChatBillingFailureRoute,
  ProtectedChatBillingSubscriptionChangedRoute:
    ProtectedChatBillingSubscriptionChangedRoute,
  ProtectedChatBillingSubscriptionSuccessRoute:
    ProtectedChatBillingSubscriptionSuccessRoute,
}

const ProtectedChatRouteWithChildren = ProtectedChatRoute._addFileChildren(
  ProtectedChatRouteChildren,
)

interface ProtectedRouteChildren {
  ProtectedChatRoute: typeof ProtectedChatRouteWithChildren
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedChatRoute: ProtectedChatRouteWithChildren,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthSignInRoute: AuthSignInRoute,
  PublicChatSlugRoute: PublicChatSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
