-- Database Seed File
--
-- Seeds the database with essential data:
-- - Subscription tier quotas (free, starter, pro, power)
-- - Stripe products and prices
--
-- 🚨 IMPORTANT: These values MUST match SUBSCRIPTION_TIER_CONFIG in src/lib/ai/models-config.ts
-- The TypeScript configuration is the SINGLE SOURCE OF TRUTH
-- Update both files together to maintain consistency
--
-- Usage:
--   Local:   pnpm db:seed:local
--   Preview: pnpm db:seed:preview
--   Prod:    pnpm db:seed:prod

-- Subscription Tier Quotas
-- Values synced with SUBSCRIPTION_TIER_CONFIG (src/lib/ai/models-config.ts)
INSERT INTO subscription_tier_quotas (id, tier, is_annual, threads_per_month, messages_per_month, memories_per_month, custom_roles_per_month, max_ai_models, allow_custom_roles, allow_memories, allow_thread_export, metadata, created_at, updated_at) VALUES ('01K6WZH2SQMZ8AH1J08DDS794H', 'free', 0, 10, 100, 5, 2, 2, 1, 1, 0, '{"description":"Basic access to 2 cheapest models","displayOrder":"1"}', 1759761697591, 1759761697591);
INSERT INTO subscription_tier_quotas (id, tier, is_annual, threads_per_month, messages_per_month, memories_per_month, custom_roles_per_month, max_ai_models, allow_custom_roles, allow_memories, allow_thread_export, metadata, created_at, updated_at) VALUES ('01K6WZH2SRVKJ92B3PT69BW83V', 'starter', 0, 50, 1000, 20, 5, 3, 1, 1, 1, '{"description":"Budget-friendly models with better performance","displayOrder":"2","stripeProductId":"prod_TAbABj98toEKg7"}', 1759761697591, 1759761697591);
INSERT INTO subscription_tier_quotas (id, tier, is_annual, threads_per_month, messages_per_month, memories_per_month, custom_roles_per_month, max_ai_models, allow_custom_roles, allow_memories, allow_thread_export, metadata, created_at, updated_at) VALUES ('01K6WZH2SRGMF6J67SJZCF401Q', 'starter', 1, 50, 1000, 20, 5, 3, 1, 1, 1, '{"description":"Budget-friendly models with better performance (annual billing)","displayOrder":"2","stripeProductId":"prod_TAbABj98toEKg7"}', 1759761697591, 1759761697591);
INSERT INTO subscription_tier_quotas (id, tier, is_annual, threads_per_month, messages_per_month, memories_per_month, custom_roles_per_month, max_ai_models, allow_custom_roles, allow_memories, allow_thread_export, metadata, created_at, updated_at) VALUES ('01K6WZH2SRFNSJNKBSTSK22Q3H', 'pro', 0, 200, 5000, 100, 20, 5, 1, 1, 1, '{"description":"Professional-grade models with excellent quality","displayOrder":"3","badge":"most_popular","stripeProductId":"prod_TAbATZPEiE2y9o"}', 1759761697591, 1759761697591);
INSERT INTO subscription_tier_quotas (id, tier, is_annual, threads_per_month, messages_per_month, memories_per_month, custom_roles_per_month, max_ai_models, allow_custom_roles, allow_memories, allow_thread_export, metadata, created_at, updated_at) VALUES ('01K6WZH2SRMC9Q3JHHQHY957XC', 'pro', 1, 200, 5000, 100, 20, 5, 1, 1, 1, '{"description":"Professional-grade models with excellent quality (annual billing)","displayOrder":"3","badge":"most_popular","stripeProductId":"prod_TAbATZPEiE2y9o"}', 1759761697591, 1759761697591);
INSERT INTO subscription_tier_quotas (id, tier, is_annual, threads_per_month, messages_per_month, memories_per_month, custom_roles_per_month, max_ai_models, allow_custom_roles, allow_memories, allow_thread_export, metadata, created_at, updated_at) VALUES ('01K6WZH2SRJCR0QV3WJ4FRYZ2G', 'power', 0, 1000, 50000, 500, 100, 8, 1, 1, 1, '{"description":"Flagship models with maximum capabilities","displayOrder":"4","stripeProductId":"prod_TAbA8kAHcag3Kb"}', 1759761697591, 1759761697591);
INSERT INTO subscription_tier_quotas (id, tier, is_annual, threads_per_month, messages_per_month, memories_per_month, custom_roles_per_month, max_ai_models, allow_custom_roles, allow_memories, allow_thread_export, metadata, created_at, updated_at) VALUES ('01K6WZH2SR2MCCWPDJ0MDZNT5Q', 'power', 1, 1000, 50000, 500, 100, 8, 1, 1, 1, '{"description":"Flagship models with maximum capabilities (annual billing)","displayOrder":"4","stripeProductId":"prod_TAbA8kAHcag3Kb"}', 1759761697591, 1759761697591);

-- Stripe Products (synced with SUBSCRIPTION_TIER_CONFIG)
-- Features reflect actual capabilities: multi-model chat, memories, custom roles, thread export
INSERT INTO stripe_product (id, name, description, active, default_price_id, metadata, images, features, created_at, updated_at) VALUES ('prod_TAbABj98toEKg7', 'Starter', 'Budget-friendly AI models with enhanced performance', 1, 'price_1SEFyVGx4IA5m8Qe8Wo4WGYK', '{"tier":"starter","displayOrder":"2"}', '[]', '["1,000 messages per month","Up to 3 concurrent AI models","50 conversations per month","20 memory slots","5 custom AI roles","Thread export","Access to budget-friendly models"]', 1759761697591, 1759761697591);
INSERT INTO stripe_product (id, name, description, active, default_price_id, metadata, images, features, created_at, updated_at) VALUES ('prod_TAbATZPEiE2y9o', 'Pro', 'Professional-grade AI models with excellent quality', 1, 'price_1SEFyWGx4IA5m8QesQBukr4b', '{"tier":"pro","displayOrder":"3","badge":"most_popular"}', '[]', '["5,000 messages per month","Up to 5 concurrent AI models","200 conversations per month","100 memory slots","20 custom AI roles","Thread export","Access to Claude 4.5 Sonnet, Gemini 2.5 Pro, GPT-4o"]', 1759761697591, 1759761697591);
INSERT INTO stripe_product (id, name, description, active, default_price_id, metadata, images, features, created_at, updated_at) VALUES ('prod_TAbA8kAHcag3Kb', 'Power', 'Flagship AI models with maximum capabilities', 1, 'price_1SEFyYGx4IA5m8QeXhso3m35', '{"tier":"power","displayOrder":"4"}', '[]', '["50,000 messages per month","Up to 8 concurrent AI models","1,000 conversations per month","500 memory slots","100 custom AI roles","Thread export","Access to GPT-5, Claude Opus 4.1, O3"]', 1759761697591, 1759761697591);

-- Stripe Prices
INSERT INTO stripe_price (id, product_id, active, currency, unit_amount, type, `interval`, interval_count, trial_period_days, metadata, created_at, updated_at) VALUES ('price_1SEFyVGx4IA5m8Qe8Wo4WGYK', 'prod_TAbABj98toEKg7', 1, 'usd', 2000, 'recurring', 'month', 1, NULL, '{"tier":"starter","billingPeriod":"monthly"}', 1759761697591, 1759761697591);
INSERT INTO stripe_price (id, product_id, active, currency, unit_amount, type, `interval`, interval_count, trial_period_days, metadata, created_at, updated_at) VALUES ('price_1SEFyVGx4IA5m8QevBWdcRom', 'prod_TAbABj98toEKg7', 1, 'usd', 20000, 'recurring', 'year', 1, NULL, '{"tier":"starter","billingPeriod":"annual","savingsPercent":"17"}', 1759761697591, 1759761697591);
INSERT INTO stripe_price (id, product_id, active, currency, unit_amount, type, `interval`, interval_count, trial_period_days, metadata, created_at, updated_at) VALUES ('price_1SEFyWGx4IA5m8QesQBukr4b', 'prod_TAbATZPEiE2y9o', 1, 'usd', 5900, 'recurring', 'month', 1, NULL, '{"tier":"pro","billingPeriod":"monthly"}', 1759761697591, 1759761697591);
INSERT INTO stripe_price (id, product_id, active, currency, unit_amount, type, `interval`, interval_count, trial_period_days, metadata, created_at, updated_at) VALUES ('price_1SEFyXGx4IA5m8QeM8s6Iu54', 'prod_TAbATZPEiE2y9o', 1, 'usd', 60000, 'recurring', 'year', 1, NULL, '{"tier":"pro","billingPeriod":"annual","savingsPercent":"15"}', 1759761697591, 1759761697591);
INSERT INTO stripe_price (id, product_id, active, currency, unit_amount, type, `interval`, interval_count, trial_period_days, metadata, created_at, updated_at) VALUES ('price_1SEFyYGx4IA5m8QeXhso3m35', 'prod_TAbA8kAHcag3Kb', 1, 'usd', 24900, 'recurring', 'month', 1, NULL, '{"tier":"power","billingPeriod":"monthly"}', 1759761697591, 1759761697591);
INSERT INTO stripe_price (id, product_id, active, currency, unit_amount, type, `interval`, interval_count, trial_period_days, metadata, created_at, updated_at) VALUES ('price_1SEFyYGx4IA5m8Qeukamf1lQ', 'prod_TAbA8kAHcag3Kb', 1, 'usd', 250000, 'recurring', 'year', 1, NULL, '{"tier":"power","billingPeriod":"annual","savingsPercent":"16"}', 1759761697591, 1759761697591);
