/**
 * Centralized Enum Exports
 *
 * Barrel exports for all domain-specific enums.
 * Import from '@/api/core/enums' for all enum needs.
 *
 * @example
 * ```ts
 * import {
 *   ChatModeSchema,
 *   ChatModes,
 *   type ChatMode,
 *   HealthStatusSchema,
 *   UIMessageRoleSchema,
 * } from '@/api/core/enums';
 * ```
 */

// AI SDK related enums (message roles, finish reasons, status)
export {
  AI_SDK_STATUSES,
  type AiSdkStatus,
  AiSdkStatuses,
  AiSdkStatusSchema,
  FINISH_REASONS,
  type FinishReason,
  FinishReasons,
  FinishReasonSchema,
  MESSAGE_PART_TYPES,
  type MessagePartType,
  MessagePartTypes,
  MessagePartTypeSchema,
  REASONING_PART_TYPES,
  type ReasoningPartType,
  ReasoningPartTypes,
  ReasoningPartTypeSchema,
  UI_MESSAGE_ROLES,
  type UIMessageRole,
  UIMessageRoles,
  UIMessageRoleSchema,
} from './ai-sdk';

// Moderator analysis and deliberation enums
export {
  AGREEMENT_STATUSES,
  type AgreementStatus,
  AgreementStatuses,
  AgreementStatusSchema,
  ANALYSIS_STATUSES,
  type AnalysisStatus,
  AnalysisStatuses,
  AnalysisStatusSchema,
  CONFIDENCE_WEIGHTINGS,
  type ConfidenceWeighting,
  ConfidenceWeightings,
  ConfidenceWeightingSchema,
  DEBATE_PHASES,
  type DebatePhase,
  DebatePhases,
  DebatePhaseSchema,
  DEFAULT_RESOLUTION,
  DEFAULT_STANCE,
  EVIDENCE_STRENGTHS,
  type EvidenceStrength,
  EvidenceStrengths,
  EvidenceStrengthSchema,
  RESOLUTION_TYPES,
  type ResolutionType,
  ResolutionTypes,
  ResolutionTypeSchema,
  STANCE_TYPES,
  type StanceType,
  StanceTypes,
  StanceTypeSchema,
  VOTE_TYPES,
  type VoteType,
  VoteTypes,
  VoteTypeSchema,
} from './analysis';

// Billing and subscription enums
export {
  BILLING_INTERVALS,
  type BillingInterval,
  BillingIntervals,
  BillingIntervalSchema,
  DEFAULT_UI_BILLING_INTERVAL,
  isUIBillingInterval,
  STRIPE_SUBSCRIPTION_STATUSES,
  type StripeSubscriptionStatus,
  StripeSubscriptionStatuses,
  StripeSubscriptionStatusSchema,
  SUBSCRIPTION_CHANGE_TYPES,
  type SubscriptionChangeType,
  SubscriptionChangeTypes,
  SubscriptionChangeTypeSchema,
  UI_BILLING_INTERVALS,
  type UIBillingInterval,
  UIBillingIntervals,
  UIBillingIntervalSchema,
  USAGE_STATUSES,
  type UsageStatus,
  UsageStatusSchema,
} from './billing';

// Chat, thread, and message enums
export {
  CHANGELOG_CHANGE_TYPES,
  CHANGELOG_TYPES,
  type ChangelogChangeType,
  ChangelogChangeTypes,
  ChangelogChangeTypeSchema,
  type ChangelogType,
  ChangelogTypes,
  ChangelogTypeSchema,
  CHAT_MODES,
  type ChatMode,
  ChatModes,
  ChatModeSchema,
  DEFAULT_CHAT_MODE,
  MESSAGE_ROLES,
  MESSAGE_STATUSES,
  type MessageRole,
  MessageRoles,
  MessageRoleSchema,
  type MessageStatus,
  MessageStatuses,
  MessageStatusSchema,
  SCREEN_MODES,
  type ScreenMode,
  ScreenModes,
  ScreenModeSchema,
  THREAD_STATUSES,
  type ThreadStatus,
  ThreadStatuses,
  ThreadStatusSchema,
} from './chat';

// Common/shared enums (includes config: Environment, SortDirection)
export {
  DATABASE_OPERATIONS,
  type DatabaseOperation,
  DatabaseOperations,
  DatabaseOperationSchema,
  type Environment,
  ENVIRONMENTS,
  Environments,
  EnvironmentSchema,
  HEALTH_STATUSES,
  type HealthStatus,
  HealthStatuses,
  HealthStatusSchema,
  HTTP_METHODS,
  type HttpMethod,
  HttpMethods,
  HttpMethodSchema,
  SORT_DIRECTIONS,
  type SortDirection,
  SortDirections,
  SortDirectionSchema,
} from './common';

// Email component enums
export {
  EMAIL_COLORS,
  EMAIL_SPACINGS,
  EMAIL_TEXT_WEIGHTS,
  type EmailColor,
  EmailColors,
  EmailColorSchema,
  type EmailSpacing,
  EmailSpacings,
  EmailSpacingSchema,
  type EmailTextWeight,
  EmailTextWeights,
  EmailTextWeightSchema,
} from './email';

// Error classification enums
export {
  AI_HISTORY_STATUSES,
  type AIHistoryStatus,
  AIHistoryStatuses,
  AIHistoryStatusSchema,
  AUTH_ACTIONS,
  AUTH_FAILURE_REASONS,
  type AuthAction,
  AuthActions,
  AuthActionSchema,
  type AuthFailureReason,
  AuthFailureReasonSchema,
  ERROR_CATEGORIES,
  ERROR_TYPES,
  ErrorCategories,
  type ErrorCategory,
  ErrorCategorySchema,
  type ErrorType,
  ErrorTypes,
  ErrorTypeSchema,
  RESOURCE_UNAVAILABLE_REASONS,
  type ResourceUnavailableReason,
  ResourceUnavailableReasonSchema,
  STREAM_ERROR_TYPES,
  type StreamErrorType,
  StreamErrorTypes,
  StreamErrorTypeSchema,
  UI_MESSAGE_ERROR_TYPES,
  type UIMessageErrorType,
  UIMessageErrorTypes,
  UIMessageErrorTypeSchema,
  VALIDATION_TYPES,
  type ValidationType,
  ValidationTypes,
  ValidationTypeSchema,
} from './errors';

// Feedback enums
export {
  FEEDBACK_TYPES,
  type FeedbackType,
  FeedbackTypes,
  FeedbackTypeSchema,
  ROUND_FEEDBACK_VALUES,
  type RoundFeedbackValue,
  RoundFeedbackValues,
  RoundFeedbackValueSchema,
} from './feedback';

// File, MIME type, and upload enums (consolidated)
export {
  ALLOWED_MIME_TYPES,
  type AllowedMimeType,
  AllowedMimeTypeSchema,
  CHAT_ATTACHMENT_STATUSES,
  type ChatAttachmentStatus,
  ChatAttachmentStatuses,
  ChatAttachmentStatusSchema,
  CODE_MIME_TYPES,
  CODE_MIMES,
  DEFAULT_CHAT_ATTACHMENT_STATUS,
  DEFAULT_FILE_CATEGORY,
  DEFAULT_FILE_PREVIEW_TYPE,
  DEFAULT_UPLOAD_STATUS,
  DEFAULT_UPLOAD_STRATEGY,
  DOCUMENT_MIME_TYPES,
  DOCUMENT_MIMES,
  FILE_CATEGORIES,
  FILE_PREVIEW_TYPE_LABELS,
  FILE_PREVIEW_TYPES,
  FILE_TYPE_LABELS,
  FILE_VALIDATION_ERROR_CODES,
  FileCategories,
  type FileCategory,
  FileCategorySchema,
  type FilePreviewType,
  FilePreviewTypes,
  FilePreviewTypeSchema,
  type FileTypeLabelMimeType,
  type FileValidationErrorCode,
  FileValidationErrorCodes,
  FileValidationErrorCodeSchema,
  getFileTypeLabelFromMime,
  IMAGE_MIME_TYPES,
  IMAGE_MIMES,
  type ImageMimeType,
  isVisualMimeType,
  MAX_FILENAME_LENGTH,
  MAX_MULTIPART_PARTS,
  MAX_SINGLE_UPLOAD_SIZE,
  MAX_TEXT_CONTENT_SIZE,
  MAX_TOTAL_FILE_SIZE,
  MIME_TYPE_CATEGORIES,
  MIN_MULTIPART_PART_SIZE,
  RECOMMENDED_PART_SIZE,
  TEXT_EXTRACTABLE_MIME_TYPES,
  TEXT_MIME_TYPES,
  TEXT_MIMES,
  type TextExtractableMimeType,
  UPLOAD_STATUSES,
  UPLOAD_STRATEGIES,
  type UploadStatus,
  UploadStatuses,
  UploadStatusSchema,
  UploadStrategies,
  type UploadStrategy,
  UploadStrategySchema,
  VISUAL_MIME_TYPES,
  type VisualMimeType,
} from './file-types';

// Model enums
export {
  DEFAULT_MODEL_CATEGORY_FILTER,
  MODEL_CATEGORIES,
  MODEL_CATEGORY_FILTERS,
  type ModelCategory,
  type ModelCategoryFilter,
  ModelCategoryFilters,
  ModelCategoryFilterSchema,
  ModelCategorySchema,
} from './models';

// Project and knowledge base enums
export {
  CITATION_PREFIXES,
  CITATION_SOURCE_TYPES,
  type CitationPrefix,
  CitationPrefixToSourceType,
  CitationSourceContentLimits,
  CitationSourceLabels,
  CitationSourcePrefixes,
  type CitationSourceType,
  CitationSourceTypes,
  CitationSourceTypeSchema,
  DEFAULT_CITATION_SOURCE_TYPE,
  DEFAULT_PROJECT_COLOR,
  DEFAULT_PROJECT_INDEX_STATUS,
  DEFAULT_PROJECT_MEMORY_SOURCE,
  PROJECT_COLORS,
  PROJECT_INDEX_STATUSES,
  PROJECT_MEMORY_SOURCES,
  type ProjectColor,
  ProjectColors,
  ProjectColorSchema,
  type ProjectIndexStatus,
  ProjectIndexStatuses,
  ProjectIndexStatusSchema,
  type ProjectMemorySource,
  ProjectMemorySources,
  ProjectMemorySourceSchema,
} from './project';

// Prompt template enums
export {
  DEFAULT_PLACEHOLDER_PREFIX,
  PLACEHOLDER_PREFIXES,
  type PlaceholderPrefix,
  PlaceholderPrefixes,
  PlaceholderPrefixSchema,
} from './prompts';

// Streaming and flow state enums
export {
  CHAIN_OF_THOUGHT_STEP_STATUSES,
  type ChainOfThoughtStepStatus,
  ChainOfThoughtStepStatuses,
  ChainOfThoughtStepStatusSchema,
  DEFAULT_FLOW_STATE,
  FLOW_STATES,
  type FlowState,
  FlowStates,
  FlowStateSchema,
  OPERATION_STATUSES,
  type OperationStatus,
  OperationStatuses,
  OperationStatusSchema,
  PARTICIPANT_STREAM_STATUSES,
  type ParticipantStreamStatus,
  ParticipantStreamStatuses,
  ParticipantStreamStatusSchema,
  PENDING_MESSAGE_VALIDATION_REASONS,
  type PendingMessageValidationReason,
  PendingMessageValidationReasons,
  PendingMessageValidationReasonSchema,
  ROUND_PHASES,
  type RoundPhase,
  RoundPhases,
  RoundPhaseSchema,
  STREAM_STATUSES,
  STREAMING_EVENT_TYPES,
  type StreamingEventType,
  type StreamStatus,
  StreamStatuses,
  StreamStatusSchema,
} from './streaming';

// UI component enums
export {
  COMPONENT_SIZES,
  COMPONENT_VARIANTS,
  type ComponentSize,
  ComponentSizes,
  ComponentSizeSchema,
  type ComponentVariant,
  ComponentVariants,
  ComponentVariantSchema,
  REASONING_STATES,
  type ReasoningState,
  ReasoningStates,
  ReasoningStateSchema,
  TEXT_ALIGNMENTS,
  type TextAlignment,
  TextAlignments,
  TextAlignmentSchema,
  TOAST_VARIANTS,
  type ToastVariant,
  ToastVariants,
  ToastVariantSchema,
} from './ui';

// Web search enums
export {
  DEFAULT_PRE_SEARCH_QUERY_STATE_STATUS,
  DEFAULT_WEB_SEARCH_CONTENT_TYPE,
  MAX_QUERY_COUNTS,
  type MaxQueryCount,
  MaxQueryCountSchema,
  PRE_SEARCH_QUERY_STATE_STATUSES,
  PRE_SEARCH_QUERY_STATUSES,
  PRE_SEARCH_SSE_EVENTS,
  PRE_SEARCH_STATUSES,
  type PreSearchQueryStateStatus,
  PreSearchQueryStateStatuses,
  PreSearchQueryStateStatusSchema,
  type PreSearchQueryStatus,
  PreSearchQueryStatuses,
  PreSearchQueryStatusSchema,
  type PreSearchSseEvent,
  PreSearchSseEvents,
  PreSearchSseEventSchema,
  type PreSearchStatus,
  PreSearchStatuses,
  PreSearchStatusSchema,
  QUERY_ANALYSIS_COMPLEXITIES,
  QueryAnalysisComplexities,
  type QueryAnalysisComplexity,
  QueryAnalysisComplexitySchema,
  type QueryAnalysisResult,
  QueryAnalysisResultSchema,
  SEARCH_RESULT_STATUSES,
  type SearchResultStatus,
  SearchResultStatuses,
  SearchResultStatusSchema,
  UNKNOWN_DOMAIN,
  WEB_SEARCH_ANSWER_MODES,
  WEB_SEARCH_COMPLEXITIES,
  WEB_SEARCH_CONTENT_TYPES,
  WEB_SEARCH_DEPTHS,
  WEB_SEARCH_RAW_CONTENT_FORMATS,
  WEB_SEARCH_STREAMING_STAGES,
  WEB_SEARCH_TIME_RANGES,
  WEB_SEARCH_TOPICS,
  type WebSearchAnswerMode,
  WebSearchAnswerModes,
  WebSearchAnswerModeSchema,
  WebSearchComplexities,
  type WebSearchComplexity,
  WebSearchComplexitySchema,
  type WebSearchContentType,
  WebSearchContentTypes,
  WebSearchContentTypeSchema,
  type WebSearchDepth,
  WebSearchDepths,
  WebSearchDepthSchema,
  type WebSearchRawContentFormat,
  WebSearchRawContentFormats,
  WebSearchRawContentFormatSchema,
  type WebSearchStreamingStage,
  WebSearchStreamingStages,
  WebSearchStreamingStageSchema,
  type WebSearchTimeRange,
  WebSearchTimeRanges,
  WebSearchTimeRangeSchema,
  type WebSearchTopic,
  WebSearchTopics,
  WebSearchTopicSchema,
} from './web-search';
