/* eslint-disable */
// CloudflareEnv type declarations for the API package
// This should be generated by `wrangler types` but is manually defined for type checking

declare namespace Cloudflare {
  interface Env {
    // KV Namespace
    KV: KVNamespace;

    // D1 Database
    DB: D1Database;

    // R2 Buckets
    UPLOADS_R2_BUCKET: R2Bucket;

    // Durable Objects
    UPLOAD_CLEANUP_SCHEDULER: DurableObjectNamespace;

    // Queues
    TITLE_GENERATION_QUEUE: Queue;
    ROUND_ORCHESTRATION_QUEUE: Queue;

    // AI/Browser bindings
    BROWSER: Fetcher;
    AI: Ai;

    // Environment variables
    NODE_ENV: string;
    WEBAPP_ENV: string;
    APP_NAME: string;
    APP_VERSION: string;
    R2_PUBLIC_URL: string;
    MAINTENANCE?: string;

    // Turnstile
    TURNSTILE_SITE_KEY: string;
    TURNSTILE_SECRET_KEY: string;

    // AWS SES
    AWS_SES_ACCESS_KEY_ID: string;
    AWS_SES_SECRET_ACCESS_KEY: string;
    AWS_SES_REGION: string;
    FROM_EMAIL: string;
    SES_REPLY_TO_EMAIL: string;
    SES_VERIFIED_EMAIL: string;

    // Better Auth
    BETTER_AUTH_SECRET: string;
    BETTER_AUTH_URL: string;
    AUTH_GOOGLE_ID: string;
    AUTH_GOOGLE_SECRET: string;

    // Stripe
    STRIPE_SECRET_KEY: string;
    STRIPE_PUBLISHABLE_KEY: string;
    STRIPE_CUSTOMER_PORTAL_CONFIG_ID: string;
    STRIPE_WEBHOOK_SECRET: string;

    // OpenRouter
    OPENROUTER_API_KEY: string;

    // PostHog
    POSTHOG_API_KEY: string;
    POSTHOG_HOST: string;
  }
}

interface CloudflareEnv extends Cloudflare.Env {}
